############################
# Author : H0llyW00dzZ     #
############################
name: Gopher Unit Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
        default: 'master'

jobs:
  test:
    name: Run Gopher Unit Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Temporarily removed `windows-latest` due to some issues with Windows. However, my code is correct lmao.
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.21.5']

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod tidy

    - name: Run tests
      run: |
        go test -v -timeout 30s -run '^(TestProcessCSVOption|TestPromptForInput|TestPromptForInputCancellation|TestLoadTestSessionsInvalidPath|TestLoadIncorrectJson|TestRepairJSONDataFromFile|TestWriteContentToFile)' github.com/H0llyW00dzZ/ChatGPT-Next-Web-Session-Exporter
